version: '3.8'

services:
  app-dev:
    image: api-user-management-v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/app/libs
    networks:
      - app-network
    env_file:
      - /home/ubuntu/environment/Project/Envs/dev.env

  app-hml:
    image: api-user-management-v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=hml
    ports:
      - "8081:8080"  # Expondo a porta 8081 para o ambiente de homologação
    volumes:
      - ./build/libs:/app/libs
    networks:
      - app-network
    env_file:
      - /home/ubuntu/environment/Project/Envs/hml.env

networks:
  app-network:
    driver: bridge
